Twitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path

from .views import register_user,login_user, logout_user

urlpatterns = [
    path('login/', login_user),
    path('logout/', logout_user),
    path('register/', register_user)
]

posts/urls.py
from django.urls import path

from .views import *

app_name = 'post'

urlpatterns = [
    path('', timeline, name='timeline'),
    path('compose/tweet/', post_create, name='create'),
    path('status/<int:id>/', post_detail, name='detail'),
    path('status/<int:id>/update', post_update, name='update'),
    path('status/<int:id>/delete', post_delete, name='delete'),
    path('status/<int:id>/like', like_post, name='like-post'),
    path('status/<int:id>/retweet', retweet_post, name='retweet-post'),
    path('status/<int:id>/likes', post_likes_list, name='like-list'),
    path('status/<int:id>/retweets', post_retweet_list, name='retweet-list'),

    
    path('status/<int:id>/comment', post_comment, name='post-comment')
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.urls import reverse

User = settings.AUTH_USER_MODEL


class Post(models.Model):
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    content = models.TextField(max_length=280)
    retweets = models.IntegerField(default=0)
    quote_tweets = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    file = models.FileField(upload_to='uploads', null=True, blank=True)

    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'id': self.id})

    def __str__(self):
        return self.content

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.post.content} - {self.user}'

class Retweet(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.post.content} - {self.user}'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.post.content} - {self.user} - {self.comment}'

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import redirect, render

def register_user(request):
    if request.user.is_authenticated:
        return redirect('/logout')

    form = UserCreationForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('/login')

    context = {
        'form':form
    }

    return render(request, 'accounts/register.html', context)

def login_user(request):

    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()

            login(request, user)
            return redirect('/')

    else:
        form = AuthenticationForm()

    context = {
        'form': form
    }


    return render(request, 'accounts/login.html', context)

        

def logout_user(request):

    if request.user.is_authenticated:

        if request.method == 'POST':
            logout(request)
            return redirect('/login')

        return render(request, 'accounts/logout.html')

    
    return redirect('/login')

posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse

from .forms import PostForm, CommentForm
from .models import Post, Like, Retweet, Comment

from django.conf import settings
User = settings.AUTH_USER_MODEL

User = get_user_model()


@login_required
def timeline(request):
    posts = Post.objects.all().order_by('-timestamp')

    context = {
        'posts': posts,
        'form': PostForm()
    }

    return render(request, 'posts/timeline.html', context)


@login_required
def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    comment = Comment.objects.filter(post=post)
    form = CommentForm()

    context = {
        'post':post,
        'form': form,
        'comments': comment
    }

    return render(request, 'posts/detail.html', context)



@login_required
def post_update(request, id):
    post = get_object_or_404(Post, id=id)

    if request.user != post.author:
        return HttpResponse('you cant update this post')

    form = PostForm(request.POST or None, instance=post)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {
        'form': form
    }
    return render(request, 'posts/create.html', context)

@login_required
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)

    if request.user != post.author:
        return HttpResponse('you can"t delete this post')

    if request.method == 'POST':
        post.delete()
        return redirect('/')

    context = {
        'object': post
    }
    return render(request, 'delete.html', context)


def post_likes_list(request, id):

    post_like_list = None

    if id is not None:
        post_liked = Post.objects.get(id=id)
        post_like_list = post_liked.like_set.all()

    content = {
        'likes_list': post_like_list
    }


    return render(request, 'posts/like-list.html', content)


def like_post(request, id):

    post_liked = Post.objects.get(id=id)

    query = None

    try:
        query = Like.objects.get(post=post_liked, user=request.user)
    except :
        pass

    if query:
        query.delete()
    else:
        Like.objects.create(post=post_liked, user=request.user)

    return redirect('/')    


def post_retweet_list(request, id):
    post_retweet_list = None

    if id is not None:
        post_retweeted = Post.objects.get(id=id)
        post_retweet_list = post_retweeted.retweet_set.all()

    content = {
        'likes_list': post_retweet_list,
        'type': 'Retweets'
    }


    return render(request, 'posts/like-list.html', content)

def retweet_post(request, id):

    post_retweeted = Post.objects.get(id=id)

    query = None

    try:
        query = Retweet.objects.get(post=post_retweeted, user=request.user)
    except :
        pass

    if query:
        query.delete()
    else:
        Retweet.objects.create(post=post_retweeted, user=request.user)
    
    # Retweet.objects.create(post=post_retweeted, user=request.user)

    return redirect('/') 

@login_required
def post_create(request):

    form = PostForm(request.POST)

    if form.is_valid():
        post_object = form.save(commit=False)
        post_object.author = request.user
        post_object.save()
        return redirect('/')

@login_required 
def post_comment(request, id):
    post = get_object_or_404(Post, id=id)

    form = CommentForm(request.POST)

    if request.method == 'POST':
        if form.is_valid():
            obj = form.save(commit=False)
            obj.post = post
            obj.user = request.user
            obj.save()
            
            form = CommentForm()

    return redirect(f"/status/{id}/") #change this later to use  name

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    {% if error %}
    <p style="color: red;">{{ error }}</p>
    {% endif  %}
    <br>

    <form action="" method="post">
        {% csrf_token %}
        
        {{ form.as_p }}

        <button>Login</button>
    </form>

    Don't Have an Account? <a href="/register">Sign Up</a>


{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}


    <form action="" method="post">
        {% csrf_token %}
        <h2>Log out of Twitter?</h2>

        You can always log back in at any time. 
        If you just want to switch accounts, 
        you can do that by adding an existing account. 

        <button>Logout</button>
    </form>

    <a href="/" >Cancel</a>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Sign Up</button>
</form>

Have an Account? <a href="/login">login</a>

{% endblock %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Post</button>
</form>

{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block content %}

    <div>
        --------------------------------------
        <br>
        {{ post.content }} 

        <br>
        -----------------------------------

        <br>

        <a href="{% url 'post:retweet-list' post.id %}">{{ post.retweet_set.count }} retweet{{ post.retweet_set.count|pluralize }}</a>
        <a href="q">{{ post.quote_tweets }} Quote Tweets</a>
        <a href="{% url 'post:like-list' post.id %}">{{ post.like_set.count }} Like{{ post.like_set.count|pluralize }} </a>
         <br>
         <br>

         <!-- <a href="{{ post.get_absolute_url }}"> reply</a>
        <a href="{% url 'post:retweet-post' post.id %}">retweet</a>
        <a href="{% url 'post:like-post' post.id %}">like </a> -->

        <form action="{% url 'post:post-comment' post.id %}" method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button><Section>Reply</Section></button>
        </form>

        <br>

        <h3>Comments</h3>

        {% for comment in comments %}
            

            {{ comment.user }} {{ comment.username }} <br>

            replying to @{{ post.author }} <br> 

            {{ comment.comment }} <br>
            <br>

        {% endfor %}

        <br>
        


    </div>

    <br>

{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Post</button>
</form>

<br>
 <br>

{% for post in posts %}
    <div>
        {{ post.author.first_name }} <br>
        @{{ post.author.username }} <br>

        {% if request.user == post.author %}

        <a href="{% url 'post-update' post.id%}">edit</a>
        <a href="{% url 'post-delete' post.id%}">delete</a>

        {% endif %}

        <br>

        --------------------------------------
        <br>
        <a href="{{ post.get_absolute_url }}">{{ post.content }} </a>
        <br>


        <a href="{{ post.get_absolute_url }}">{{ post.comment_set.count }} comment</a>
        <a href="{% url 'retweet-post' post.id %}">{{ post.retweet_set.count }} retweets</a>
        <a href="q">{{ post.quote_tweets }} Quote Tweets</a>
        <a href="{% url 'like-post' post.id %}">{{ post.like_set.count }} Likes </a>

        <br>
        
    </div>
    
    <br> <br>
{% endfor %}

{% endblock %}

posts/templates/posts/like-list.html
{% extends 'base.html' %}

{% block content %}

    {% if type == 'Retweets' %}

    Retweeted by:

    {% else %}

    liked by:

    {% endif %}

    <ul>
        {% for x in likes_list %}

            <li>{{ x.user }}</li>

        {% endfor %}

    </ul>

{% endblock %}

posts/templates/posts/timeline.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'post:create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Post</button>
</form>

<br>
 <br>

{% for post in posts %}
    <div>
        {{ post.author.first_name }} <br>
        @{{ post.author.username }} 

        {% if request.user == post.author %}

        <a href="{% url 'post:update' post.id%}">edit</a>
        <a href="{% url 'post:delete' post.id%}">delete</a>

        {% endif %}

        <br>

        --------------------------------------
        <br>
        <br>
        <a href="{{ post.get_absolute_url }}">{{ post.content }} </a>
        <br>
        <br>
        -------------------------------------- <br>


        <a href="{{ post.get_absolute_url }}">{{ post.comment_set.count }} comment{{ post.comment_set.count|pluralize }}</a>
        <a href="{% url 'post:retweet-post' post.id %}">{{ post.retweet_set.count }} retweet{{ post.retweet_set.count|pluralize }}</a>
        <!-- <a href="q">{{ post.quote_tweets }} Quote Tweets</a> -->
        <a href="{% url 'post:like-post' post.id %}">{{ post.like_set.count }} Like{{ post.like_set.count|pluralize }} </a>

        <br>
        
    </div>
    
    <br> <br>

{% empty %}

No Post yet...

{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="https://unpkg.com/htmx.org@1.7.0" 
        integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" 
        crossorigin="anonymous" defer>
    </script>

    <title>Twitter </title>
</head>
<body>
    <nav>Navbar</nav>
    <a href="/">Home</a>

    {% if request.user.is_authenticated %}

    <a href="/logout">Logout</a>

    {% else %}
    <a href="/login">Login</a>
    {% endif %}



    <hr>

    {% comment %}

    {% include 'search/search-form.html' %}

    {% endcomment %}

    <br><br>
    {% block content %}

    {% endblock content %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        
        Are you sure you want to delete {{ object}}


        <button type="submit">Yes, Delete</button>

        <button type="button"><a href="/">No, Cancel</a></button>

    </form>


{% endblock %}